version: '3.3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 9003
    working_dir: /var/app
    volumes:
      - .:/var/app
